### PR TITLE
Added Enchantment  and Enchantment  level

### PR DESCRIPTION
**Pull request by hexosse**

### CODE REVIEW

**Comment by Meow-J** [comment]
I don't know why but it does break the potions(Maybe due to the change of spigot api). You can use `gradle test` to see the errors

**Comment by hexosse** [comment]
Potions of regen did not passed the tests before I add enchantements.
I had to comment the two last test.
But, I'll check it

**Comment by Meow-J** [comment]
it's kinda weird, I use the latest version of Spigot API to build again, no errors found

**Comment by Meow-J** [comment]
BTW, I may not reply in time, cause I'm not at home

**Comment by hexosse** [comment]
Just re downloaded LanguageUtils and launch ```gradle test``` :

```
java.lang.NullPointerException
	at org.bukkit.potion.PotionEffectTypeWrapper.isInstant(PotionEffectTypeWrapper.java:29)
	at org.bukkit.potion.PotionType.isInstant(PotionType.java:48)
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408)
	at org.bukkit.potion.Potion.fromItemStack(Potion.java:418)
	at com.meowj.langutils.lang.convert.EnumPotionEffect.getLocalizedName(EnumPotionEffect.java:111)
	at com.meowj.langutils.lang.LanguageHelper.getItemName(LanguageHelper.java:69)
	at com.meowj.langutils.lang.LanguageHelper.getItemDisplayName(LanguageHelper.java:43)
	at com.meowj.langutils.lang.LanguageHelperTest.testPotionDisplayName(LanguageHelperTest.java:84)
```

**Comment by Meow-J** [comment]
All right, I'll merge it, and then fix it a few days later

**Comment by Meow-J** [comment]
Obviously, the latest version of Spigot breaks the `isInstant()` method. Originally, this error only occurs to Instant Health Potion.

**Comment by Meow-J** [comment]
All right, I found the [problem](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/48c241290f235fece1ec7d08ea4421c1c67aa9a8). I need to implement a PotionEffectType myself in order to pass the test.

**Pull request merged**
